import { User, Item } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Adam Baker',
    email: 'adam.seth.baker@gmail.com',
    phone: '+15555550101',
    friends: ['user-2', 'user-3', 'user-4'],
  },
  {
    id: 'user-2',
    name: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    phone: '+15555550102',
    friends: ['user-1', 'user-3'],
    itemVisibility: 'both',
  },
  {
    id: 'user-3',
    name: 'Mike Chen',
    email: 'mike.c@example.com',
    phone: '+15555550103',
    friends: ['user-1', 'user-2'],
    itemVisibility: 'both',
  },
  {
    id: 'user-4',
    name: 'Lisa Rodriguez',
    email: 'lisa.r@example.com',
    phone: '+15555550104',
    friends: ['user-1'],
    itemVisibility: 'both',
  },
];

const d = (daysFromNow: number) => {
  const dt = new Date();
  dt.setDate(dt.getDate() + daysFromNow);
  return dt.toISOString();
};

export const MOCK_ITEMS: Item[] = [
  {
    id: 'item-1',
    donorId: 'user-2',
    title: 'IKEA KALLAX Bookshelf (4x4)',
    description:
      'White 4x4 KALLAX bookshelf in great condition. Minor scratch on the lower-right side panel. Dimensions: 57" x 57". You must be able to disassemble and transport.',
    photos: [],
    condition: 'good',
    pickupLocation: '123 Maple St, Springfield',
    pickupWindow: 'Weekends, 10am–4pm',
    disposalDate: d(7),
    disposalMethod: 'goodwill',
    claimPickupHours: 72,
    status: 'available',
    waitlist: [],
    createdAt: d(-2),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'item-2',
    donorId: 'user-3',
    title: 'Infant Car Seat (Graco SnugRide 35)',
    description:
      'Graco SnugRide 35 infant car seat with base. Expires 2028. Never involved in an accident. Cleaned and ready to go. Fits children 4–35 lbs.',
    photos: [],
    condition: 'excellent',
    restrictions: 'For pregnant friends or families with newborns only',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Any evening after 6pm, Mon–Fri',
    disposalDate: d(14),
    disposalMethod: 'salvation_army',
    claimPickupHours: 48,
    status: 'available',
    waitlist: [],
    createdAt: d(-1),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'item-3',
    donorId: 'user-4',
    title: 'Twin Bed Frame & Mattress',
    description:
      'Metal twin bed frame + mattress. Mattress has always had a protector on it and is in great shape. Frame disassembles easily. Headboard included.',
    photos: [],
    condition: 'good',
    restrictions: 'Foster care placements only — caseworker documentation required',
    pickupLocation: '789 Pine Rd, Springfield',
    pickupWindow: 'Saturday mornings, 8am–noon',
    disposalDate: d(5),
    disposalMethod: 'habitat',
    claimPickupHours: 96,
    status: 'claimed',
    claimedBy: 'user-2',
    claimDeadline: d(2),
    waitlist: [],
    createdAt: d(-3),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'item-4',
    donorId: 'user-2',
    title: 'Kitchen Starter Box',
    description:
      'Assorted kitchen items — mixing bowls (set of 3), spatulas, measuring cups, colander, can opener, and a few utensils. Great for someone setting up a first kitchen.',
    photos: [],
    condition: 'fair',
    pickupLocation: '123 Maple St, Springfield',
    pickupWindow: 'Weekends, 10am–4pm',
    disposalDate: d(2),
    disposalMethod: 'goodwill',
    claimPickupHours: 24,
    status: 'available',
    waitlist: [],
    createdAt: d(-1),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'item-5',
    donorId: 'user-3',
    title: 'Standing Desk (adjustable height)',
    description:
      'Electric sit-stand desk. 60" x 30" surface. Control panel works perfectly. Slight scuff on the left corner. Must pick up with help — it\'s heavy.',
    photos: [],
    condition: 'good',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Weekends only',
    disposalDate: d(10),
    disposalMethod: 'goodwill',
    claimPickupHours: 72,
    status: 'available',
    waitlist: ['user-1'],
    createdAt: d(-4),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // ── Borrow listings ──────────────────────────────────────────────────────────

  {
    id: 'borrow-1',
    donorId: 'user-2',
    title: 'Dewalt Power Drill Set',
    description: 'Dewalt 20V cordless drill/driver with two batteries, charger, and a 30-piece bit set. Perfect for hanging shelves or assembling furniture. Just return it clean and with both batteries charged.',
    photos: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&q=80'],
    condition: 'excellent',
    pickupLocation: '123 Maple St, Springfield',
    pickupWindow: 'Weekends, 10am–4pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-3),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [
      { start: d(14).slice(0, 10), end: d(21).slice(0, 10), note: 'Out of town' },
    ],
  },
  {
    id: 'borrow-2',
    donorId: 'user-3',
    title: 'Carpet Cleaner (Bissell ProHeat)',
    description: 'Bissell ProHeat 2X carpet cleaner. Works great on pet stains and high-traffic areas. Comes with the upholstery attachment. Please rinse the tank before returning.',
    photos: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'],
    condition: 'good',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Any evening after 6pm, or weekends',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'borrowed',
    borrowedBy: 'user-1',
    borrowedUntil: d(4).slice(0, 10),
    waitlist: [],
    createdAt: d(-5),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-2-1',
        requesterId: 'user-1',
        startDate: d(-2).slice(0, 10),
        endDate: d(4).slice(0, 10),
        status: 'approved',
        createdAt: d(-3),
      },
    ],
    blockedPeriods: [],
  },
  {
    id: 'borrow-3',
    donorId: 'user-4',
    title: 'Instant Pot Duo 8-Quart',
    description: '8-quart Instant Pot with all original accessories — trivet, steam rack, sealing rings. Great for batch cooking or holiday meals. Will fit up to a 7 lb whole chicken.',
    photos: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80'],
    condition: 'excellent',
    pickupLocation: '789 Pine Rd, Springfield',
    pickupWindow: 'Anytime with 24h notice',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-1),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-3-1',
        requesterId: 'user-1',
        startDate: d(3).slice(0, 10),
        endDate: d(7).slice(0, 10),
        status: 'pending',
        createdAt: d(-1),
      },
    ],
    blockedPeriods: [],
  },
  {
    id: 'borrow-4',
    donorId: 'user-2',
    title: 'Projector + 100" Screen',
    description: 'Epson 1080p home theater projector with a 100" pull-down screen and HDMI cable. Ideal for movie nights or sports watch parties. ~3,000 hours left on the lamp.',
    photos: ['https://images.unsplash.com/photo-1536240478700-b869ad10e128?w=600&q=80'],
    condition: 'good',
    pickupLocation: '123 Maple St, Springfield',
    pickupWindow: 'Weekends, 10am–4pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-6),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [
      { start: d(30).slice(0, 10), end: d(37).slice(0, 10), note: 'Reserved for family reunion' },
    ],
  },
  {
    id: 'borrow-5',
    donorId: 'user-3',
    title: 'Folding Tables + Chairs (Set of 8)',
    description: 'Four 6-foot folding tables and eight folding chairs — great for parties, garage sales, or holiday gatherings. Clean and sturdy. Tables fold flat for easy transport in most SUVs.',
    photos: ['https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80'],
    condition: 'good',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Weekends only',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-2),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-6',
    donorId: 'user-4',
    title: 'KitchenAid Stand Mixer',
    description: 'Classic KitchenAid 5-quart tilt-head stand mixer in Empire Red. Comes with dough hook, flat beater, and whisk. Perfect for holiday baking. Please return with all three attachments.',
    photos: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80'],
    condition: 'excellent',
    pickupLocation: '789 Pine Rd, Springfield',
    pickupWindow: 'Evenings after 5pm or weekends',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-4),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [
      { start: d(60).slice(0, 10), end: d(67).slice(0, 10), note: 'Thanksgiving week' },
    ],
  },
  {
    id: 'borrow-7',
    donorId: 'user-2',
    title: 'Pressure Washer (2300 PSI)',
    description: 'Electric 2300 PSI pressure washer with 25-foot hose, three nozzle tips, and soap dispenser. Great for driveways, decks, siding, and patio furniture. Extension cord not included.',
    photos: ['https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=600&q=80'],
    condition: 'good',
    pickupLocation: '123 Maple St, Springfield',
    pickupWindow: 'Weekends, 10am–4pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'pending_return',
    borrowedBy: 'user-4',
    borrowedUntil: d(1).slice(0, 10),
    waitlist: [],
    createdAt: d(-10),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-7-1',
        requesterId: 'user-4',
        startDate: d(-7).slice(0, 10),
        endDate: d(1).slice(0, 10),
        status: 'approved',
        createdAt: d(-8),
      },
    ],
    blockedPeriods: [],
  },
  {
    id: 'borrow-8',
    donorId: 'user-3',
    title: 'Baby Swing (4moms mamaRoo)',
    description: '4moms mamaRoo 4 infant swing — 5 unique motions, Bluetooth, built-in sounds. Used for 4 months, in excellent shape. Comes with the seat insert and all original parts.',
    photos: ['https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80'],
    condition: 'excellent',
    restrictions: 'Families with infants under 6 months only',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Any evening after 5:30pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-7),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-9',
    donorId: 'user-4',
    title: 'Rooftop Cargo Carrier',
    description: 'Thule Motion XT rooftop cargo box — 16 cubic feet, fits ski/snowboard gear or luggage for a road trip. Comes with universal fit mounting kit. Max load 165 lbs.',
    photos: ['https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=80'],
    condition: 'good',
    pickupLocation: '789 Pine Rd, Springfield',
    pickupWindow: 'Weekends only, arrange by Friday',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-2),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-9-1',
        requesterId: 'user-1',
        startDate: d(5).slice(0, 10),
        endDate: d(12).slice(0, 10),
        status: 'pending',
        createdAt: d(-1),
      },
      {
        id: 'br-9-2',
        requesterId: 'user-2',
        startDate: d(8).slice(0, 10),
        endDate: d(14).slice(0, 10),
        status: 'pending',
        createdAt: d(-1),
      },
    ],
    blockedPeriods: [],
  },
  {
    id: 'borrow-10',
    donorId: 'user-3',
    title: 'Garment Steamer (Jiffy)',
    description: 'Jiffy professional garment steamer — heats up in 60 seconds, 1.2L tank, 45 min run time. Great before weddings, photo shoots, or job interviews. Comes with fabric brush and hanger attachment.',
    photos: ['https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80'],
    condition: 'excellent',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Mon–Fri after 7pm, or Saturday',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-1),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },
];
