import { User, Item } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Adam Baker',
    email: 'adam.seth.baker@gmail.com',
    phone: '+15555550101',
    friends: ['user-2', 'user-3', 'user-4'],
  },
  {
    id: 'user-2',
    name: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    phone: '+15555550102',
    friends: ['user-1', 'user-3'],
    itemVisibility: 'both',
  },
  {
    id: 'user-3',
    name: 'Mike Chen',
    email: 'mike.c@example.com',
    phone: '+15555550103',
    friends: ['user-1', 'user-2'],
    itemVisibility: 'both',
  },
  {
    id: 'user-4',
    name: 'Lisa Rodriguez',
    email: 'lisa.r@example.com',
    phone: '+15555550104',
    friends: ['user-1'],
    itemVisibility: 'both',
  },
  {
    id: 'user-5',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    phone: '+15035550105',
    friends: ['user-6', 'user-7', 'user-8', 'user-9', 'user-10', 'user-11', 'user-12', 'user-13', 'user-14'],
    itemVisibility: 'both',
  },
  {
    id: 'user-6',
    name: 'Carlos Mendez',
    email: 'carlos.mendez@example.com',
    phone: '+13055550106',
    friends: ['user-5', 'user-7', 'user-8', 'user-9', 'user-10', 'user-11', 'user-12', 'user-13', 'user-14'],
    itemVisibility: 'both',
  },
  {
    id: 'user-7',
    name: 'Jessica Wu',
    email: 'jessica.wu@example.com',
    phone: '+17135550107',
    friends: ['user-5', 'user-6', 'user-8', 'user-9', 'user-10', 'user-11', 'user-12', 'user-13', 'user-14'],
    itemVisibility: 'both',
  },
  {
    id: 'user-8',
    name: 'David Kim',
    email: 'david.kim@example.com',
    phone: '+16195550108',
    friends: ['user-5', 'user-6', 'user-7', 'user-9', 'user-10', 'user-11', 'user-12', 'user-13', 'user-14'],
    itemVisibility: 'both',
  },
  {
    id: 'user-9',
    name: 'Rachel Green',
    email: 'rachel.green@example.com',
    phone: '+16155550109',
    friends: ['user-5', 'user-6', 'user-7', 'user-8', 'user-10', 'user-11', 'user-12', 'user-13', 'user-14'],
    itemVisibility: 'both',
  },
  {
    id: 'user-10',
    name: 'Omar Hassan',
    email: 'omar.hassan@example.com',
    phone: '+16125550110',
    friends: ['user-5', 'user-6', 'user-7', 'user-8', 'user-9', 'user-11', 'user-12', 'user-13', 'user-14'],
    itemVisibility: 'both',
  },
  {
    id: 'user-11',
    name: 'Stephanie Lee',
    email: 'stephanie.lee@example.com',
    phone: '+15035550111',
    friends: ['user-5', 'user-6', 'user-7', 'user-8', 'user-9', 'user-10', 'user-12', 'user-13', 'user-14'],
    itemVisibility: 'both',
  },
  {
    id: 'user-12',
    name: 'Ben Torres',
    email: 'ben.torres@example.com',
    phone: '+12155550112',
    friends: ['user-5', 'user-6', 'user-7', 'user-8', 'user-9', 'user-10', 'user-11', 'user-13', 'user-14'],
    itemVisibility: 'both',
  },
  {
    id: 'user-13',
    name: 'Megan O\'Brien',
    email: 'megan.obrien@example.com',
    phone: '+16175550113',
    friends: ['user-5', 'user-6', 'user-7', 'user-8', 'user-9', 'user-10', 'user-11', 'user-12', 'user-14'],
    itemVisibility: 'both',
  },
  {
    id: 'user-14',
    name: 'Andre Jackson',
    email: 'andre.jackson@example.com',
    phone: '+15045550114',
    friends: ['user-5', 'user-6', 'user-7', 'user-8', 'user-9', 'user-10', 'user-11', 'user-12', 'user-13'],
    itemVisibility: 'both',
  },
];

const d = (daysFromNow: number) => {
  const dt = new Date();
  dt.setDate(dt.getDate() + daysFromNow);
  return dt.toISOString();
};

export const MOCK_ITEMS: Item[] = [
  {
    id: 'item-1',
    donorId: 'user-2',
    title: 'IKEA KALLAX Bookshelf (4x4)',
    description:
      'White 4x4 KALLAX bookshelf in great condition. Minor scratch on the lower-right side panel. Dimensions: 57" x 57". You must be able to disassemble and transport.',
    photos: [],
    condition: 'good',
    pickupLocation: '123 Maple St, Springfield',
    pickupWindow: 'Weekends, 10am–4pm',
    disposalDate: d(7),
    disposalMethod: 'goodwill',
    claimPickupHours: 72,
    status: 'available',
    waitlist: [],
    createdAt: d(-2),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'item-2',
    donorId: 'user-3',
    title: 'Infant Car Seat (Graco SnugRide 35)',
    description:
      'Graco SnugRide 35 infant car seat with base. Expires 2028. Never involved in an accident. Cleaned and ready to go. Fits children 4–35 lbs.',
    photos: [],
    condition: 'excellent',
    restrictions: 'For pregnant friends or families with newborns only',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Any evening after 6pm, Mon–Fri',
    disposalDate: d(14),
    disposalMethod: 'salvation_army',
    claimPickupHours: 48,
    status: 'available',
    waitlist: [],
    createdAt: d(-1),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'item-3',
    donorId: 'user-4',
    title: 'Twin Bed Frame & Mattress',
    description:
      'Metal twin bed frame + mattress. Mattress has always had a protector on it and is in great shape. Frame disassembles easily. Headboard included.',
    photos: [],
    condition: 'good',
    restrictions: 'Foster care placements only — caseworker documentation required',
    pickupLocation: '789 Pine Rd, Springfield',
    pickupWindow: 'Saturday mornings, 8am–noon',
    disposalDate: d(5),
    disposalMethod: 'habitat',
    claimPickupHours: 96,
    status: 'pending_pickup',
    claimedBy: 'user-2',
    waitlist: [],
    createdAt: d(-3),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'item-4',
    donorId: 'user-2',
    title: 'Kitchen Starter Box',
    description:
      'Assorted kitchen items — mixing bowls (set of 3), spatulas, measuring cups, colander, can opener, and a few utensils. Great for someone setting up a first kitchen.',
    photos: [],
    condition: 'fair',
    pickupLocation: '123 Maple St, Springfield',
    pickupWindow: 'Weekends, 10am–4pm',
    disposalDate: d(2),
    disposalMethod: 'goodwill',
    claimPickupHours: 24,
    status: 'available',
    waitlist: [],
    createdAt: d(-1),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'item-5',
    donorId: 'user-3',
    title: 'Standing Desk (adjustable height)',
    description:
      'Electric sit-stand desk. 60" x 30" surface. Control panel works perfectly. Slight scuff on the left corner. Must pick up with help — it\'s heavy.',
    photos: [],
    condition: 'good',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Weekends only',
    disposalDate: d(10),
    disposalMethod: 'goodwill',
    claimPickupHours: 72,
    status: 'claimed',
    claimedBy: 'user-1',
    claimDeadline: d(1),
    waitlist: [],
    createdAt: d(-4),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // ── Adam Baker (user-1) listings ─────────────────────────────────────────────

  {
    id: 'item-user1-1',
    donorId: 'user-1',
    title: 'Peloton Bike+ (Gen 2)',
    description: 'Peloton Bike+ in great shape — touchscreen, auto-resistance, and 2 years of classes remaining on the subscription (transferable). Includes shoes (size 10), weights, and mat. Upgrading to a rower.',
    photos: [],
    condition: 'excellent',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Weekends only — bring help, it\'s heavy',
    disposalDate: d(14),
    disposalMethod: 'goodwill',
    claimPickupHours: 72,
    status: 'pending_pickup',
    claimedBy: 'user-2',
    waitlist: ['user-3'],
    createdAt: d(-5),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'item-user1-2',
    donorId: 'user-1',
    title: 'Dyson V11 Cordless Vacuum',
    description: 'Dyson V11 Torque Drive with two cleaner heads, three accessories, wall dock, and two batteries. Excellent suction. Upgrading to a V15.',
    photos: [],
    condition: 'good',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Any day after 5pm',
    disposalDate: d(30),
    disposalMethod: 'goodwill',
    claimPickupHours: 48,
    status: 'picked_up',
    claimedBy: 'user-3',
    waitlist: [],
    createdAt: d(-10),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-user1-1',
    donorId: 'user-1',
    title: 'Werner 24ft Extension Ladder',
    description: 'Werner D1224-2 24-foot aluminum extension ladder, Type I (250 lb rated). Solid condition, rubber feet in great shape. Great for gutters, painting, or roof work.',
    photos: [],
    condition: 'good',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Weekends, 9am–5pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-7),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-u1-1',
        requesterId: 'user-2',
        startDate: d(3).slice(0, 10),
        endDate: d(6).slice(0, 10),
        status: 'pending',
        createdAt: d(-1),
      },
      {
        id: 'br-u1-2',
        requesterId: 'user-3',
        startDate: d(8).slice(0, 10),
        endDate: d(11).slice(0, 10),
        status: 'pending',
        createdAt: d(-1),
      },
    ],
    blockedPeriods: [],
  },
  {
    id: 'borrow-user1-2',
    donorId: 'user-1',
    title: 'Canopy Party Tent (10×20)',
    description: '10×20 ft heavy-duty pop-up canopy tent with sidewalls, stakes, and carry bag. Fits up to 30 people. Great for backyard parties, graduation events, or farmers markets.',
    photos: [],
    condition: 'good',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Any day with 24h notice',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'borrowed',
    borrowedBy: 'user-4',
    borrowedUntil: d(5).slice(0, 10),
    waitlist: [],
    createdAt: d(-12),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-u1-3',
        requesterId: 'user-4',
        startDate: d(-2).slice(0, 10),
        endDate: d(5).slice(0, 10),
        status: 'approved',
        createdAt: d(-4),
      },
    ],
    blockedPeriods: [],
  },
  {
    id: 'borrow-user1-3',
    donorId: 'user-1',
    title: 'DeWalt 7-1/4" Circular Saw',
    description: 'DeWalt DWE575SB 7-1/4" lightweight circular saw with electric brake. One blade included. Great for deck boards, plywood, framing lumber. Return with blade guard on.',
    photos: [],
    condition: 'excellent',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Weekends, 9am–5pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'pending_return',
    borrowedBy: 'user-2',
    borrowedUntil: d(-1).slice(0, 10),
    waitlist: [],
    createdAt: d(-20),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-u1-4',
        requesterId: 'user-2',
        startDate: d(-10).slice(0, 10),
        endDate: d(-1).slice(0, 10),
        status: 'approved',
        createdAt: d(-12),
      },
    ],
    blockedPeriods: [],
  },

  // ── Adam Baker (user-1) — additional listings ────────────────────────────────

  // Give — available with two people on waitlist
  {
    id: 'item-user1-3',
    donorId: 'user-1',
    title: 'Sonos Play:1 Speaker Pair',
    description: 'Two Sonos Play:1 speakers set up as a stereo pair. Both work perfectly — just moved to a soundbar setup. Includes power cables and original boxes. App-based setup takes about 5 minutes.',
    photos: [],
    condition: 'excellent',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Evenings after 6pm or weekends',
    disposalDate: d(21),
    disposalMethod: 'goodwill',
    claimPickupHours: 48,
    status: 'available',
    waitlist: ['user-2', 'user-3'],
    createdAt: d(-8),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // Give — claimed with 4-hour urgent deadline
  {
    id: 'item-user1-4',
    donorId: 'user-1',
    title: 'Calphalon 10-Piece Cookware Set',
    description: 'Calphalon Contemporary nonstick 10-piece set — 8" and 10" skillets, 1.5qt and 2.5qt saucepans with lids, 3qt sauté pan with lid, and 8qt stock pot with lid. 4 years old but well-maintained.',
    photos: [],
    condition: 'good',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Any day after 5pm',
    disposalDate: d(7),
    disposalMethod: 'goodwill',
    claimPickupHours: 24,
    status: 'claimed',
    claimedBy: 'user-2',
    claimDeadline: new Date(Date.now() + 4 * 3600000).toISOString(),
    waitlist: ['user-4'],
    createdAt: d(-3),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // Give — claimed but pickup window EXPIRED (triggers donor expiry banner)
  {
    id: 'item-user1-5',
    donorId: 'user-1',
    title: 'Weber Spirit E-310 Gas Grill',
    description: 'Weber Spirit E-310 3-burner propane grill. Grates cleaned, igniter works. Small rust spot on the left side panel — cosmetic only. Cover and full tank of propane included. Moving to a condo.',
    photos: [],
    condition: 'good',
    restrictions: 'Must have a truck or SUV — will not fit in a sedan.',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Weekends only',
    disposalDate: d(10),
    disposalMethod: 'trash',
    claimPickupHours: 48,
    status: 'claimed',
    claimedBy: 'user-3',
    claimDeadline: new Date(Date.now() - 3 * 3600000).toISOString(),
    waitlist: [],
    createdAt: d(-6),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // Give — pending_pickup (user-4 submitted, waiting for me to confirm)
  {
    id: 'item-user1-6',
    donorId: 'user-1',
    title: 'Pottery Barn Outdoor Sectional (4-piece)',
    description: '4-piece all-weather outdoor sectional from Pottery Barn — two corner chairs, armless chair, and ottoman. Cushions are weatherproof and clean. Switching to a smaller patio set.',
    photos: [],
    condition: 'good',
    restrictions: 'Truck or large SUV required — this is heavy furniture.',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Saturday mornings, 8am–noon',
    disposalDate: d(14),
    disposalMethod: 'other_charity',
    claimPickupHours: 72,
    status: 'pending_pickup',
    claimedBy: 'user-4',
    waitlist: [],
    createdAt: d(-9),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // Give — fully completed (picked_up)
  {
    id: 'item-user1-7',
    donorId: 'user-1',
    title: 'L-Shaped Executive Desk (60")',
    description: 'Dark walnut L-shaped desk, 60"x60". Two drawers on the right pedestal. Minor scuffs on the corner but structurally solid. Disassembles into 3 pieces for transport.',
    photos: [],
    condition: 'fair',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Weekends only',
    disposalDate: d(60),
    disposalMethod: 'goodwill',
    claimPickupHours: 72,
    status: 'picked_up',
    claimedBy: 'user-2',
    waitlist: [],
    createdAt: d(-30),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // Borrow — available with a blocked period coming up
  {
    id: 'borrow-user1-4',
    donorId: 'user-1',
    title: 'Solo Stove Bonfire + Stand',
    description: 'Solo Stove Bonfire 2.0 with steel stand and carry bag. Smokeless fire pit, fits 14" logs. Perfect for backyard evenings. Return clean and dry — no wet wood residue.',
    photos: [],
    condition: 'excellent',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Any day with 24h notice',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-15),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [
      { start: d(12).slice(0, 10), end: d(16).slice(0, 10), note: 'Camping weekend' },
    ],
  },

  // Borrow — available, no activity yet
  {
    id: 'borrow-user1-5',
    donorId: 'user-1',
    title: 'Vitamix 5200 Blender',
    description: 'Vitamix 5200 with 64oz container and tamper. Variable speed dial and pulse function. 7 years old but runs like new — Vitamix lasts forever. Return clean with the lid on.',
    photos: [],
    condition: 'good',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Evenings after 6pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-4),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // Borrow — actively borrowed, due in 4 days (on time)
  {
    id: 'borrow-user1-6',
    donorId: 'user-1',
    title: 'Milwaukee M18 Drill + Impact Driver Combo',
    description: 'Milwaukee M18 2-tool combo kit — drill/driver and impact driver, two 5.0Ah batteries, charger, and belt clip. Great for any home project. Return with batteries charged.',
    photos: [],
    condition: 'excellent',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Weekends, 9am–5pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'borrowed',
    borrowedBy: 'user-3',
    borrowedUntil: d(4).slice(0, 10),
    waitlist: [],
    createdAt: d(-25),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-u1-5',
        requesterId: 'user-3',
        startDate: d(-5).slice(0, 10),
        endDate: d(4).slice(0, 10),
        status: 'approved',
        createdAt: d(-7),
      },
    ],
    blockedPeriods: [],
  },

  // Borrow — borrowed and OVERDUE (due 3 days ago, borrower hasn't submitted return)
  {
    id: 'borrow-user1-7',
    donorId: 'user-1',
    title: 'DeWalt 10" Jobsite Table Saw',
    description: 'DeWalt DWE7480 10" compact jobsite table saw with 24.5" rip capacity and rack and pinion fence. Blade guard included. Return with blade clean and fence re-locked.',
    photos: [],
    condition: 'good',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Weekends, 9am–5pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'borrowed',
    borrowedBy: 'user-4',
    borrowedUntil: d(-3).slice(0, 10),
    waitlist: [],
    createdAt: d(-30),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-u1-6',
        requesterId: 'user-4',
        startDate: d(-14).slice(0, 10),
        endDate: d(-3).slice(0, 10),
        status: 'approved',
        createdAt: d(-16),
      },
    ],
    blockedPeriods: [],
  },

  // Borrow — pending_return (user-2 submitted return, I need to confirm)
  {
    id: 'borrow-user1-8',
    donorId: 'user-1',
    title: 'Traeger Pro 575 Pellet Grill',
    description: 'Traeger Pro 575 WiFi pellet grill — 575 sq in cooking area, WiFIRE app control, pellet sensor. Comes with a half-bag of hickory pellets. Return with the hopper empty and grates brushed.',
    photos: [],
    condition: 'good',
    pickupLocation: '321 Elm St, Springfield',
    pickupWindow: 'Weekends only — it\'s heavy',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'pending_return',
    borrowedBy: 'user-2',
    borrowedUntil: d(-1).slice(0, 10),
    waitlist: [],
    createdAt: d(-45),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-u1-7',
        requesterId: 'user-2',
        startDate: d(-9).slice(0, 10),
        endDate: d(-1).slice(0, 10),
        status: 'approved',
        createdAt: d(-11),
      },
    ],
    blockedPeriods: [],
  },

  // ── Borrow listings ──────────────────────────────────────────────────────────

  {
    id: 'borrow-1',
    donorId: 'user-2',
    title: 'Dewalt Power Drill Set',
    description: 'Dewalt 20V cordless drill/driver with two batteries, charger, and a 30-piece bit set. Perfect for hanging shelves or assembling furniture. Just return it clean and with both batteries charged.',
    photos: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&q=80'],
    condition: 'excellent',
    pickupLocation: '123 Maple St, Springfield',
    pickupWindow: 'Weekends, 10am–4pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-3),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [
      { start: d(14).slice(0, 10), end: d(21).slice(0, 10), note: 'Out of town' },
    ],
  },
  {
    id: 'borrow-2',
    donorId: 'user-3',
    title: 'Carpet Cleaner (Bissell ProHeat)',
    description: 'Bissell ProHeat 2X carpet cleaner. Works great on pet stains and high-traffic areas. Comes with the upholstery attachment. Please rinse the tank before returning.',
    photos: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'],
    condition: 'good',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Any evening after 6pm, or weekends',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'borrowed',
    borrowedBy: 'user-1',
    borrowedUntil: d(4).slice(0, 10),
    waitlist: [],
    createdAt: d(-5),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-2-1',
        requesterId: 'user-1',
        startDate: d(-2).slice(0, 10),
        endDate: d(4).slice(0, 10),
        status: 'approved',
        createdAt: d(-3),
      },
    ],
    blockedPeriods: [],
  },
  {
    id: 'borrow-3',
    donorId: 'user-4',
    title: 'Instant Pot Duo 8-Quart',
    description: '8-quart Instant Pot with all original accessories — trivet, steam rack, sealing rings. Great for batch cooking or holiday meals. Will fit up to a 7 lb whole chicken.',
    photos: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80'],
    condition: 'excellent',
    pickupLocation: '789 Pine Rd, Springfield',
    pickupWindow: 'Anytime with 24h notice',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-1),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-3-1',
        requesterId: 'user-1',
        startDate: d(3).slice(0, 10),
        endDate: d(7).slice(0, 10),
        status: 'pending',
        createdAt: d(-1),
      },
    ],
    blockedPeriods: [],
  },
  {
    id: 'borrow-4',
    donorId: 'user-2',
    title: 'Projector + 100" Screen',
    description: 'Epson 1080p home theater projector with a 100" pull-down screen and HDMI cable. Ideal for movie nights or sports watch parties. ~3,000 hours left on the lamp.',
    photos: ['https://images.unsplash.com/photo-1536240478700-b869ad10e128?w=600&q=80'],
    condition: 'good',
    pickupLocation: '123 Maple St, Springfield',
    pickupWindow: 'Weekends, 10am–4pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-6),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [
      { start: d(30).slice(0, 10), end: d(37).slice(0, 10), note: 'Reserved for family reunion' },
    ],
  },
  {
    id: 'borrow-5',
    donorId: 'user-3',
    title: 'Folding Tables + Chairs (Set of 8)',
    description: 'Four 6-foot folding tables and eight folding chairs — great for parties, garage sales, or holiday gatherings. Clean and sturdy. Tables fold flat for easy transport in most SUVs.',
    photos: ['https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80'],
    condition: 'good',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Weekends only',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-2),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-6',
    donorId: 'user-4',
    title: 'KitchenAid Stand Mixer',
    description: 'Classic KitchenAid 5-quart tilt-head stand mixer in Empire Red. Comes with dough hook, flat beater, and whisk. Perfect for holiday baking. Please return with all three attachments.',
    photos: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80'],
    condition: 'excellent',
    pickupLocation: '789 Pine Rd, Springfield',
    pickupWindow: 'Evenings after 5pm or weekends',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-4),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [
      { start: d(60).slice(0, 10), end: d(67).slice(0, 10), note: 'Thanksgiving week' },
    ],
  },
  {
    id: 'borrow-7',
    donorId: 'user-2',
    title: 'Pressure Washer (2300 PSI)',
    description: 'Electric 2300 PSI pressure washer with 25-foot hose, three nozzle tips, and soap dispenser. Great for driveways, decks, siding, and patio furniture. Extension cord not included.',
    photos: ['https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=600&q=80'],
    condition: 'good',
    pickupLocation: '123 Maple St, Springfield',
    pickupWindow: 'Weekends, 10am–4pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'pending_return',
    borrowedBy: 'user-4',
    borrowedUntil: d(1).slice(0, 10),
    waitlist: [],
    createdAt: d(-10),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-7-1',
        requesterId: 'user-4',
        startDate: d(-7).slice(0, 10),
        endDate: d(1).slice(0, 10),
        status: 'approved',
        createdAt: d(-8),
      },
    ],
    blockedPeriods: [],
  },
  {
    id: 'borrow-8',
    donorId: 'user-3',
    title: 'Baby Swing (4moms mamaRoo)',
    description: '4moms mamaRoo 4 infant swing — 5 unique motions, Bluetooth, built-in sounds. Used for 4 months, in excellent shape. Comes with the seat insert and all original parts.',
    photos: ['https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80'],
    condition: 'excellent',
    restrictions: 'Families with infants under 6 months only',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Any evening after 5:30pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-7),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-9',
    donorId: 'user-4',
    title: 'Rooftop Cargo Carrier',
    description: 'Thule Motion XT rooftop cargo box — 16 cubic feet, fits ski/snowboard gear or luggage for a road trip. Comes with universal fit mounting kit. Max load 165 lbs.',
    photos: ['https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=80'],
    condition: 'good',
    pickupLocation: '789 Pine Rd, Springfield',
    pickupWindow: 'Weekends only, arrange by Friday',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-2),
    listingType: 'borrow',
    borrowRequests: [
      {
        id: 'br-9-1',
        requesterId: 'user-1',
        startDate: d(5).slice(0, 10),
        endDate: d(12).slice(0, 10),
        status: 'pending',
        createdAt: d(-1),
      },
      {
        id: 'br-9-2',
        requesterId: 'user-2',
        startDate: d(8).slice(0, 10),
        endDate: d(14).slice(0, 10),
        status: 'pending',
        createdAt: d(-1),
      },
    ],
    blockedPeriods: [],
  },
  {
    id: 'borrow-10',
    donorId: 'user-3',
    title: 'Garment Steamer (Jiffy)',
    description: 'Jiffy professional garment steamer — heats up in 60 seconds, 1.2L tank, 45 min run time. Great before weddings, photo shoots, or job interviews. Comes with fabric brush and hanger attachment.',
    photos: ['https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80'],
    condition: 'excellent',
    pickupLocation: '456 Oak Ave, Springfield',
    pickupWindow: 'Mon–Fri after 7pm, or Saturday',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-1),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // ── Priya Sharma (user-5) ─────────────────────────────────────────────────

  {
    id: 'item-6',
    donorId: 'user-5',
    title: 'Lululemon Yoga Mat + Block Set',
    description: 'Lululemon The Mat 5mm in midnight navy (lightly used), two cork yoga blocks, a stretch strap, and a Manduka mat bag. Cleaned and ready to go. Switching to a studio practice.',
    photos: [],
    condition: 'excellent',
    pickupLocation: '1234 NW Burnside St, Portland, OR 97209',
    pickupWindow: 'Evenings after 6pm or weekends',
    disposalDate: d(14),
    disposalMethod: 'goodwill',
    claimPickupHours: 48,
    status: 'available',
    waitlist: [],
    createdAt: d(-2),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-11',
    donorId: 'user-5',
    title: 'Zojirushi Bread Machine',
    description: 'Zojirushi BB-PDC20 2lb bread maker — programmed for everything from white to gluten-free. Measuring cup, spoon, and kneading blade included. Returns with the paddle clean, please.',
    photos: [],
    condition: 'excellent',
    pickupLocation: '1234 NW Burnside St, Portland, OR 97209',
    pickupWindow: 'Weekends 10am–4pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-5),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // ── Carlos Mendez (user-6) ────────────────────────────────────────────────

  {
    id: 'item-7',
    donorId: 'user-6',
    title: '4-Piece Wicker Outdoor Patio Set',
    description: 'All-weather resin wicker sectional — two loveseats, a coffee table, and an armchair. Cushions are weatherproof and clean. Selling the house, can\'t take it with me.',
    photos: [],
    condition: 'good',
    restrictions: 'Must have a truck or large SUV for transport.',
    pickupLocation: '800 Brickell Ave, Miami, FL 33131',
    pickupWindow: 'Saturday or Sunday mornings',
    disposalDate: d(10),
    disposalMethod: 'other_charity',
    claimPickupHours: 72,
    status: 'available',
    waitlist: [],
    createdAt: d(-3),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-12',
    donorId: 'user-6',
    title: 'Electric Pressure Washer (3000 PSI)',
    description: 'Sun Joe SPX3001 3000 PSI pressure washer with 20-foot hose, five quick-connect nozzles, and onboard detergent tank. Great for driveways, fences, and patio furniture.',
    photos: [],
    condition: 'good',
    pickupLocation: '800 Brickell Ave, Miami, FL 33131',
    pickupWindow: 'Weekdays after 5pm or weekends',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-4),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [
      { start: d(20).slice(0, 10), end: d(27).slice(0, 10), note: 'Out of town' },
    ],
  },

  // ── Jessica Wu (user-7) ───────────────────────────────────────────────────

  {
    id: 'item-8',
    donorId: 'user-7',
    title: 'Maternity Wardrobe Box (Size S/M)',
    description: 'Box of 20+ maternity pieces — jeans, leggings, flowy tops, two work blouses, and a maxi dress. Brands include ASOS Maternity, H&M, and Motherhood. All washed and folded.',
    photos: [],
    condition: 'good',
    restrictions: 'Size small/medium pre-pregnancy (fits up to 36 weeks).',
    pickupLocation: '1801 Main St, Houston, TX 77002',
    pickupWindow: 'Any day after 5pm',
    disposalDate: d(21),
    disposalMethod: 'other_charity',
    claimPickupHours: 48,
    status: 'available',
    waitlist: [],
    createdAt: d(-1),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-13',
    donorId: 'user-7',
    title: 'Nanit Pro Baby Monitor + Floor Stand',
    description: 'Nanit Pro smart baby monitor with floor stand, breathing-wear band, and two months of Insights subscription remaining. HD video, sleep tracking, two-way audio. Just return it with the stand folded.',
    photos: [],
    condition: 'excellent',
    restrictions: 'Families with infants under 12 months only.',
    pickupLocation: '1801 Main St, Houston, TX 77002',
    pickupWindow: 'Evenings after 6pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-6),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // ── David Kim (user-8) ────────────────────────────────────────────────────

  {
    id: 'item-9',
    donorId: 'user-8',
    title: 'Shortboard Surfboard (6\'2") + Wetsuit',
    description: 'Firewire 6\'2" shortboard in great shape — no delams, two small dings on the rail (repaired). Includes a 3/2mm O\'Neill Psychofreak fullsuit (size medium) and a board sock.',
    photos: [],
    condition: 'good',
    restrictions: 'Best for intermediate surfers, ~150–185 lbs.',
    pickupLocation: '1000 Kettner Blvd, San Diego, CA 92101',
    pickupWindow: 'Weekends, arrange by Friday',
    disposalDate: d(14),
    disposalMethod: 'keep',
    claimPickupHours: 72,
    status: 'available',
    waitlist: [],
    createdAt: d(-4),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-14',
    donorId: 'user-8',
    title: 'Tern GSD Cargo E-Bike',
    description: 'Tern GSD S10 long-tail cargo e-bike — dual battery, 400 lb payload, 10-speed Shimano Deore, hydraulic disc brakes. Can carry two kids or a week of groceries. Comes with two helmets.',
    photos: [],
    condition: 'excellent',
    pickupLocation: '1000 Kettner Blvd, San Diego, CA 92101',
    pickupWindow: 'Weekends only',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-2),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [
      { start: d(10).slice(0, 10), end: d(17).slice(0, 10), note: 'In for tune-up' },
    ],
  },

  // ── Rachel Green (user-9) ─────────────────────────────────────────────────

  {
    id: 'item-10',
    donorId: 'user-9',
    title: 'Yamaha FG800 Acoustic Guitar + Hard Case',
    description: 'Yamaha FG800 dreadnought acoustic guitar — solid spruce top, nato back and sides. Light pick marks near the soundhole, frets in great shape. Includes a TSA-lockable SKB hard case and a tuner clip.',
    photos: [],
    condition: 'good',
    pickupLocation: '100 Broadway, Nashville, TN 37201',
    pickupWindow: 'Afternoons Mon–Sat',
    disposalDate: d(30),
    disposalMethod: 'goodwill',
    claimPickupHours: 72,
    status: 'available',
    waitlist: [],
    createdAt: d(-7),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-15',
    donorId: 'user-9',
    title: 'Brother SE700 Embroidery Machine',
    description: 'Brother SE700 computerized sewing and embroidery machine with 135 built-in designs, 7"x5" hoop, and USB port for custom patterns. All accessories included. Please return threaded and cleaned.',
    photos: [],
    condition: 'excellent',
    pickupLocation: '100 Broadway, Nashville, TN 37201',
    pickupWindow: 'Evenings after 6pm or weekends',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-3),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // ── Omar Hassan (user-10) ─────────────────────────────────────────────────

  {
    id: 'item-11',
    donorId: 'user-10',
    title: 'Salomon Cross-Country Ski Set (170cm)',
    description: 'Complete classic XC ski set: Salomon 170cm skis, Salomon bindings, Salomon Escape 7 boots (size 10), and Swix carbon poles (140cm). Waxed and ready. Moving to Arizona.',
    photos: [],
    condition: 'good',
    restrictions: 'Fits approximately a size 10 ski boot / men\'s 10 shoe.',
    pickupLocation: '100 Washington Ave S, Minneapolis, MN 55401',
    pickupWindow: 'Weekends 9am–1pm',
    disposalDate: d(21),
    disposalMethod: 'goodwill',
    claimPickupHours: 72,
    status: 'available',
    waitlist: [],
    createdAt: d(-5),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-16',
    donorId: 'user-10',
    title: 'REI Co-op Half Dome 4-Person Tent',
    description: 'REI Half Dome 4+ tent — freestanding double-wall design, 63" peak height, two doors and vestibules. Stakes, guylines, footprint, and stuff sack all included. Great for camping or backyard sleepovers.',
    photos: [],
    condition: 'good',
    pickupLocation: '100 Washington Ave S, Minneapolis, MN 55401',
    pickupWindow: 'Any day after 5pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-8),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [
      { start: d(35).slice(0, 10), end: d(42).slice(0, 10), note: 'Family camping trip' },
    ],
  },

  // ── Stephanie Lee (user-11) ───────────────────────────────────────────────

  {
    id: 'item-12',
    donorId: 'user-11',
    title: 'Vinyl Record Collection (75+ LPs)',
    description: 'Curated collection of 75+ LPs — heavy on jazz (Coltrane, Miles, Monk), soul (Marvin Gaye, Aretha), and classic rock. Most are VG+ or better. Full tracklist available on request. Downsizing.',
    photos: [],
    condition: 'good',
    pickupLocation: '2233 NW Westover Rd, Portland, OR 97210',
    pickupWindow: 'Saturdays 11am–4pm',
    disposalDate: d(14),
    disposalMethod: 'other_charity',
    claimPickupHours: 96,
    status: 'available',
    waitlist: [],
    createdAt: d(-10),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-17',
    donorId: 'user-11',
    title: 'Sony A7III Mirrorless Camera Kit',
    description: 'Sony A7III body with 28-70mm kit lens, 50mm f/1.8, two NP-FZ100 batteries, charger, 64GB card, and a Peak Design wrist strap. Great for events, portraits, or street photography. Return with batteries charged.',
    photos: [],
    condition: 'excellent',
    pickupLocation: '2233 NW Westover Rd, Portland, OR 97210',
    pickupWindow: 'Evenings after 6pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-6),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [
      { start: d(25).slice(0, 10), end: d(28).slice(0, 10), note: 'Wedding shoot' },
    ],
  },

  // ── Ben Torres (user-12) ──────────────────────────────────────────────────

  {
    id: 'item-13',
    donorId: 'user-12',
    title: 'Herman Miller Aeron Chair (Size B)',
    description: 'Fully loaded Herman Miller Aeron in graphite — PostureFit SL, adjustable arms, lumbar support. Size B (fits up to 6\'2" / 185 lbs). Some minor scuffs on the base, everything functions perfectly. Retail $1,400+.',
    photos: [],
    condition: 'good',
    pickupLocation: '1500 Market St, Philadelphia, PA 19102',
    pickupWindow: 'Weekends only — bring help, it\'s heavy',
    disposalDate: d(21),
    disposalMethod: 'keep',
    claimPickupHours: 72,
    status: 'available',
    waitlist: [],
    createdAt: d(-3),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-18',
    donorId: 'user-12',
    title: 'Large Format Paper Cutter (24")',
    description: 'Swingline ClassicCut 24" rotary trimmer — cuts up to 10 sheets at once, replacement blade included. Great for art projects, invitations, photos, or school presentations.',
    photos: [],
    condition: 'good',
    pickupLocation: '1500 Market St, Philadelphia, PA 19102',
    pickupWindow: 'Any day after 4pm',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-2),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // ── Megan O'Brien (user-13) ───────────────────────────────────────────────

  {
    id: 'item-14',
    donorId: 'user-13',
    title: 'XL Dog Crate + Orthopedic Bed',
    description: 'Impact collapsible dog crate (42"L x 28"W x 30"H) — fits labs, goldens, border collies. Comes with a matching Orvis memory-foam orthopedic bed. Dog adopted a crate-free lifestyle. Both clean and like new.',
    photos: [],
    condition: 'excellent',
    restrictions: 'Please only claim if you have a large breed. Crate won\'t fit in a sedan.',
    pickupLocation: '100 Boylston St, Boston, MA 02116',
    pickupWindow: 'Any morning before noon',
    disposalDate: d(30),
    disposalMethod: 'goodwill',
    claimPickupHours: 48,
    status: 'available',
    waitlist: [],
    createdAt: d(-4),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-19',
    donorId: 'user-13',
    title: 'Drum Floor Sander (Clarke American)',
    description: 'Clarke American EZ-8 drum floor sander — great for refinishing hardwood floors. Comes with a full sleeve of 60-grit and 100-grit sandpaper (about 80% used), plus an edge sander. Return with dust bag emptied.',
    photos: [],
    condition: 'good',
    pickupLocation: '100 Boylston St, Boston, MA 02116',
    pickupWindow: 'Weekends only',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-9),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },

  // ── Andre Jackson (user-14) ───────────────────────────────────────────────

  {
    id: 'item-15',
    donorId: 'user-14',
    title: 'Lodge Cast Iron Cookware Set (5 pieces)',
    description: 'Lodge 5-piece cast iron set: 8" skillet, 10" skillet, 12" skillet with lid, and a 5-quart dutch oven with lid. All pre-seasoned and well-maintained. Moving into a smaller place with an induction cooktop.',
    photos: [],
    condition: 'good',
    pickupLocation: '900 Canal St, New Orleans, LA 70112',
    pickupWindow: 'Evenings after 6pm or Saturday mornings',
    disposalDate: d(14),
    disposalMethod: 'other_charity',
    claimPickupHours: 72,
    status: 'available',
    waitlist: [],
    createdAt: d(-2),
    listingType: 'give',
    borrowRequests: [],
    blockedPeriods: [],
  },
  {
    id: 'borrow-20',
    donorId: 'user-14',
    title: 'Fender Semi-Hollow Electric Guitar + Amp',
    description: 'Fender Starcaster semi-hollow in aged natural finish — coil-tapped humbuckers, great for jazz, blues, and indie. Paired with a Fender Frontman 15G practice amp. Both in great shape. Return with strings intact.',
    photos: [],
    condition: 'excellent',
    pickupLocation: '900 Canal St, New Orleans, LA 70112',
    pickupWindow: 'Any evening or weekend',
    disposalDate: '2099-12-31T00:00:00.000Z',
    disposalMethod: 'keep',
    claimPickupHours: 0,
    status: 'available',
    waitlist: [],
    createdAt: d(-5),
    listingType: 'borrow',
    borrowRequests: [],
    blockedPeriods: [],
  },
];
